// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO4z1W9wYiUQ81GBNKpwxQCgYsgdxVRv0',
    appId: '1:565842489196:web:a20d841b39cd1cf994cd49',
    messagingSenderId: '565842489196',
    projectId: 'shelf-cloud',
    authDomain: 'shelf-cloud.firebaseapp.com',
    storageBucket: 'shelf-cloud.appspot.com',
    measurementId: 'G-9QTR1PP25H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7jWACdtWGg6m_x7ROes4s3NwOn0IrcmE',
    appId: '1:565842489196:android:8656e30b64978e8894cd49',
    messagingSenderId: '565842489196',
    projectId: 'shelf-cloud',
    storageBucket: 'shelf-cloud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFbmVNBQLNn_C5sruEmdN1MDh_Tv1J7Zk',
    appId: '1:565842489196:ios:00864c1c5b01eaa694cd49',
    messagingSenderId: '565842489196',
    projectId: 'shelf-cloud',
    storageBucket: 'shelf-cloud.appspot.com',
    iosBundleId: 'com.spandin.shelfcloud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFbmVNBQLNn_C5sruEmdN1MDh_Tv1J7Zk',
    appId: '1:565842489196:ios:03add1706044fbd394cd49',
    messagingSenderId: '565842489196',
    projectId: 'shelf-cloud',
    storageBucket: 'shelf-cloud.appspot.com',
    iosBundleId: 'com.spandin.shelfcloud.RunnerTests',
  );
}
